---
title: "Analysis of Evolutionary Algorithms for Optimisation"
author:   
  - name: "Shvet Maharaj"
    student-id: "MHRSHV001"
date: last-modified
date-format: "D MMMM YYYY"
bibliography: references.bib
format:
  pdf:
    pdf-engine: pdflatex
    toc: true
    toc-depth: 4
    number-sections: true
    number-depth: 2
    toc-title: "Table of contents"
    lof: false
    lot: false
    papersize: "a4paper"
    include-in-header: 
      - text: |
          \newcommand{\B}[1]{\boldsymbol{#1}}
          \newcommand{\+}{\phantom{-}}
          \newcommand{\op}[1]{\operatorname{#1}}
keep-tex: true
execute:
  include: false
---


# Design



## Update procedures
Where noted, a _strictly improving update procedure_ will be used alongside the updating equations, defined as: 
$$\B x_{k+1} = \begin{cases}\B v_{k+1}&\text{if} \quad \op f(\B v_{k+1})< \op f(\B x_k),\\\B x_k & \text{otherwise.}\end{cases}$$
Where $\B x_k$ is the best performing point at iteration $k$, and 
$\B v_{k+1}$ is the candidate point for the next iteration, $k+1$. 
This candidate point is what is generated by the updating equations.

Alternatively, the update procedure could be a simple iterative updating procedure, where each updated point, $\B v_{k+1}$, is used directly by the algorithm in the next iteration (thus, the algorithm updates on $\B v_k$, instead of $\B x_k$). This would correspond more so to the deterministic algorithms. The best solution, $\B x_k$ is simply stored as the algorithm progresses. 

## Updating equations
At the core of this exploration of the genetic algorithm, and other methods for optimisation, are the _updating equations_. These define how exactly the optimisation paradigm attempts to iteratively improve a candidate solution, $\B v$.

### Hessian methods
#### Newton-Raphson

$$\B x_{k+1} = \B v_k -\frac{f'\left(\B v_k\right)}{f''\left(\B v_k\right)}$$

### Gradient methods
#### Gradient descent

$$\B v_{k+1} = \B v_k -\nu \nabla f\left( \B v_k \right),$$
where $\nu$ is the learning rate.


### Function value methods 
Also known as Direct Search, Pattern Search, or Black-Box Methods.
These algorithms do not make use of gradient nor of hessian information. This makes them far easier to apply to any context. 

#### Random search (RS)
The specific version of the random search algorithm is informed by the descriptions given in @zabinsky2011. Algorithms are described by being 'global' or 'local'.

**Pure Random Search (PRS)** repeatedly performs a global search with a simply improving update procedure.

The updating equation is defined as,
$$\B v_{k+1} = \B u.$$

It is notable that neither of the terms $\B x_k$ nor $\B v_k$ — the best or candidate points found by or for iteration $k$ — are present in this formula. 

Each generated point is _independent_ of any previous point. The major benefit of this is PRS is 'embarrassingly parallelisable'. This is the only optimisation algorithm that will have this property in this paper.

We test also an additional variant of RS, where the global search is either performed solely for the starting point), $\B x_0$, or skipped entirely in favour of a user-defined starting point. Subsequent points are generated locally from the hypersphere (the '($N-1$)-sphere', or the 'surface of the $N$-ball') around $\B x_k$.

This is Rastrigin's **Fixed Step Size Random Search (FSSRS)**[@rastrigin1963].

An efficient way to sample uniformly from the surface of an $N$-ball is given by @marsaglia1972.

$$\B v_{k+1} = \B x_k +h \B u,$$

Here, $\B u$ is a normalised $N$-dimensional vector sample from the standard normal distribution such that,

$\B u = \frac1{\lVert \B z \rVert}\B z$ and $\B z \sim \mathcal{N}_N\left(0,1\right),$
and where $h$ is a step size hyperparameter.


#### Genetic algorithms
Genetic algorithms are a subset of evolutionary algorithms, typified by the use of all of three genetic operators: crossover, selection, and mutation. 
A _real-coded_ (in reference to $\mathbb R$, the real number set) genetic algorithm is used for greater applicability to arbitrary problems and models, despite genetic processes occurring with a discrete set of genes (ACGT) in nature.

Notation does shift here, due to the genetic algorithm necessarily requiring multiple candidates for each iteration. Our previous notation referencing a single candidate per iteration is thus no longer feasible. 

We are implementing genetic algorithms using the `GA` package, as described in @scrucca2013. 

A brief explanation of the updating procedure follows.

##### Fitness evaluation
Fitness for each of the 'genotypes' (candidate solutions), $\theta_i^{\left(k\right)}$ is calculated, where $i$ is an arbitrary index of the genotype in the generation $k$. This is typically the objective function of interest, $\op f\left(\cdot\right)$. 

##### Selection
A subset of genotypes from the current generation's population becomes selected as a separate population known as the 'reproducing population' Genotypes are selected (with replacement) through a weighted selection process, based typically proportionally on the fitness of each genotype, $\op f\left(\theta_i^{\left(k\right)}\right)$, with probability $p_i^{\left(k\right)}$.

An elitist strategy can be used, which means that even if the best performers are unluckily not selected, they still make it to the next population. By default `gareal_lsSelection` is used, which is proportional selection with fitness linear scaling.

##### Crossover
The core of a genetic algorithm, the crossover operation, brings a means to generate additional 'child' (next generation) genotypes through parts of the 'genetic information' (parameter values) from either of the 'parent' (current generation) genotypes. Alongside mutation, crossover applied on the reproducing population creates the new, next generation population. By default, `gareal_laCrossover` is used, which is local arithmetic crossover.


##### Mutation
The randomly shifting of the values of 'genes' (parameters) within genotypes. The probability of mutation can be set by the user. Alongside crossover, mutation applied on the reproducing population creates the new, next generation population. By default, `gareal_raMutation` is used, which is uniform random mutation.


Crossover and mutation operations increase diversity in a population, allowing us to explore more of the sample space (exploration), while selection operations decrease diversity in favour of increased fitness (exploitation).


[//]: # ( shhh it's a comment
# Conclusion
## Areas for extension 
<!--aka, how i don't go down too many rabbit holes while working on this-->
Testing additional random search algorithms:
- Luus–Jaakola (LJ)
- Improving Hit-and-Run (IHR)
- Simulated Annealing
)
