---
title: "Optimisation Functions"
format: html
---


Some code is taken / adapted from Analytics Assignment 2.

# Setup

```{r}
#| label: load-libraries
library(tidyverse,attach.required = TRUE)
library(future)
library(doFuture)
library(progressr)
library(parallelly)
```

```{r}
#| label: parallel-computing-setup

options(parallelly.availableCores.omit = 1)
if(supportsMulticore()) # multicore = mac, linux, etc. (outside of RStudio)
  plan(multicore) else plan(multisession) #multisession = windows and other
on.exit(plan(sequential)) # to ensure that the workers are correctly shut down
```

```{r}
#| label: datavis-setup

base_theme <- theme_minimal() + 
  theme(aspect.ratio=1,legend.position = 'bottom')
theme_set(base_theme) # setting the default theme for ggplot 
```

# Optimisation Functions

```{r}
#| label: optimisation-function-definitions

# from scratch

gradient_descent <- function(theta){
  
}

random_search <- function(theta){
  
}

newtons_method <- function(theta){
  
}

```

```{r}
#| label: genetic-algorithm

# this genetic algorithm does not make use of a larger 'population' to which 
# the offspring are added to. The offspring become the entire population for 
# the next generation. 
# Parents are selected from the resulting population weighted by a
# performance metric.

# single-point crossover
genetic_algorithm <- function(Theta, scores=rep(1L,nrow(Theta))){
  # default 'scores' corresponds to even weighting across all genes 
  # (score=1 for all genomes)
  g <- nrow(Theta)
  stopifnot(g%%2==0)  #num of genomes must be a multiple of 2 
  p <- ncol(Theta)    #num of genes
  
  Theta_new <- crossover_recombination(Theta, scores) #g and p can be calculated within, but is it cheaper to perhaps calculate once and pass it along each generation?
  
}

crossover_recombination <- function(Theta,scores){
  g <- nrow(Theta)    # num genomes
  stopifnot(g%%2==0)  # num of genomes must be a multiple of 2 
  n <- g/2            # num pairs
  p <- ncol(Theta)    # num genes
  crossmat <- create_crossover_matrix(g,n,p,scores)
 
  # should be able to post/premultiply in a way that gives us the resulting matrix we want
  # PRE multiply
  # each row of the matrix we premult by will represent the target row
  # the column marked with 1 will give the row which will be placed in the target row
  
  parents <- crossmat[,1:2] |> t() |> matrix(ncol=1)
  # transpose to ensure the correct order is used to fill the matrix 
  # (byrow has no effect, it always goes down the column first)
  # now we will have a single column with integers in them.
  # each row is in the correct place, it is just to use the integer
  # to tell us where to place the 1 (all else being 0)
  # if can do this, then we will have the parents in the right place
  # now just to crossover...ahhhh
  
  xindex <- crossmat[,3] #cross-over point index
  
  base <- matrix(0L,ncol=g,nrow=g)
  for (i in 1:g)
  {
    base[i,parents[i]] <- 1L
  }
  selected_genomes <- base %*% Theta
  
  transformed_genomes <- selected_genomes
  for(i in 2*(1:n))
  {
    transformed_genomes[(i-1):i,xindex[i]:p] <- selected_genomes[i:(i-1),xindex[i]:p]
    # in theory, this works well
    # the subset-to-be-flipped is replaced with the (row-flipped) subset 
    # from the original
  }
}

# columns 1:2 represent the parents
# column 3 is the crossover point
# g: num of genomes (parents)
# p: num of genes / parameters within each genome
create_crossover_matrix <- function(g,n,p,scores){
  
  return(
    cbind(
      t(replicate(n, sample(g, size=2, prob=scores))), #selects 2 parents
      sample(p, n, replace=TRUE) #selects crossover point
    ) 
  )
  
  #note: will randomly crossover an amount of 'genes' from 1:num(genes)
  #thus the crossover cannot be 'no crossover', but it can be 'ALL crossover', 
  #resulting in offspring identical to the parents in only one case.
}

# to evaluate the scores applied to each parent based on some (arbitrary)
# performance metric
score_genomes <- function(Theta) {
  scores <- future_pmap(Theta,.f=objective,.progress=TRUE)
  return(scores)
}
```

```{r}
#| label: optimisation-function-definition

# wrapper function to select optimisation function
optimisation <- function(){
  
}

```

```{r}
#| label: test-function-definitions

# to be used as potential objective functions

# constrained to 2-dimensional test functions (for now) 
# (some are already generalised to any D)

#separable
#min: all x_i = 0
sphere <- function(x){
  t(x)%*%x
}
#min: c
sphere_offset <- function(x,c){
  sphere(x-c)
}




```

```{r}
#| label: objective-function-definition

objective <- function(){ # param = ?

}

```

```{r}
#| label: drone-game-objective
# one of our arbitrary objectives!

# game params
n_obst    <- 40 #J
obst_size <- 0.02 #r (radius) 2*r = square side length

delta <- 0.05
iterlim <- 100 #k

bounds <- matrix(c(-1,1,  #X_1
                   -1,1), #X_2
                 nrow=2, byrow=FALSE)
colnames(bounds) <- c('X_1','X_2')
rownames(bounds) <- c('min','max')

start_bounds <- bounds #copy, so there's no need to rename again lol
start_bounds[1:2,1:2] <- matrix(c(-0.8,0.8,
                                    -1, -1
                                  ), ncol=2)
obst_bounds <- bounds
obst_bounds[1:2,1:2] <- matrix(c(  -1, 1,
                                 -0.5, 1), ncol=2)


# theta needs to be defined such that all the game parameters are present, such that the model can 'see' the details of the game
# anything not present in the theta parameters is 'unknown' to the model or 
# "assumed" by the model (i.e., universal properties -> dimensionality = 2) 

# theta structure:
# num obstacles / trees
# obstacle size (future: sizes?)
# obstacle locations (x-y pairs)
#

#boundary points
corner_bl  <- bounds[1,] #minimums (bottom left)
corner_tr  <- bounds[2,] #maximums (top right)
corner_br  <- c(corner_tr[1],corner_bl[2]) #bottom right
corner_tl  <- c(corner_bl[1],corner_tr[2]) #top left

start_l    <- c(start_bounds[1,]) #left
start_r    <- c(start_bounds[2,]) #right

lines <- matrix(c(
  corner_bl, start_l,   #bottom_l
  start_l,   start_r,   #start
  start_r,   corner_br, #bottom_r
  corner_bl, corner_tl, #left
  corner_br, corner_tr, #right
  corner_tl, corner_tr  #top/end
), ncol=4, byrow=TRUE) |> as_tibble() 
colnames(lines) <- c('x_1','x_2','x_1.end','x_2.end')

lines <- lines |> add_column(
  "colour"=c("bound",
             "start",
             "bound",
             "bound",
             "bound",
             "finish")
  )

generate_field <- function(colours){
  return(
    ggplot() + 
      geom_segment(data=lines,aes(x=x_1,
                              y=x_2,
                              xend=x_1.end,
                              yend=x_2.end,
                              colour=colour),
                   show.legend = FALSE) +
      scale_colour_manual(values=colours) +
      scale_x_continuous(sec.axis = sec_axis(transform = ~.* 1, 
                                             name = "North")) +
      scale_y_continuous(sec.axis = sec_axis(transform = ~.* 1, 
                                             name = "East")) +
      labs(x= "South", y="West")
      
  )
}

generate_obstacles <- function(obst, fillcolour='forestgreen'){ 
  return(
    geom_tile(data = obst,
              fill = fillcolour, 
              aes(x=X_1, y=X_2,
                  height=2*Size,
                  width =2*Size
                  #fill  = fillcolour
                  )
              )
  )
  # chose to plot trees as squares instead of circles for plotting accuracy -
  # i.e., the plot matches exactly the reality of the game (except that the 
  # corners of the trees do not cause collision). 
  # The size of the trees are exactly what is shown.
}

detect_collision <- function(x){
  if(abs(x[1]) >= bounds[2,1] || x[2] <= bounds[1,2]) #boundary detection
  {
    return(1)
  }
  
  # object detection
  J <- nrow(obst)
  dists <- abs((matrix(1,nrow=J,ncol=1) %*% x) - obst[,-3]) 
  
  col <- (dists > obst[,3]) #since comparisons are faster than float-pt mult
  # tests if outside Manhattan distance (outside the 'square tree'
  # i.e., as represented in the plots)
  
  # now, tests only the trees for which the drone is within the 'square tree'
  # testing the actual circle hitbox :o
  
  o <- !(col[,1]|col[,2])
  
  d <- rowSums(dists[o,,drop=FALSE]**2) #should be faster than matrix 
  # multiplication, then extracting diagonals?
  
  if (any(d<=obst[o,3]))
    return(1)
  
  return(0) # no collisions!
}

eval_game_state <- function(x){
  if (iterlim > 100 || detect_collision(x,obst))
    return(-1)  
  
  if (x[2] >= bounds[2,2])
    return(1)
  
  return(0)
}

on_game_loss <- function(){
  
}
on_game_win <- function(){
  
}
```


# Neural Network

Later potential additions: ability to set layer amount & size through a list of integers

```{r}
#| label: nn-structure
#| echo: true
# ------------------------------- model data ------------------------------
m <- c(5,5) #hidden layer size
M <- length(m) #num hidden layers
p <- 2  #predictors
q <- 2  #responses
N <- dat |> nrow()
X <- dat[,  1:p] |> as.matrix(ncol=p, nrow=N)
Y <- dat[,p+1:q] |> as.matrix(ncol=q, nrow=N)
npars <- p*m[1] +m[1]*m[2] +m[2]*q +m[1]+m[2]+q # =57
# --- activation functions ------------------------------------------------
sig1 <- function(z) tanh(z)     # first m hidden layer
sig2 <- function(z) tanh(z)     # second m hidden layer
sig3 <- function(z) softmax(z)  # output layer
# --- neural network ------------------------------------------------------
neural_net <- function(X, Y, theta, m, nu) {
  N <- X |> nrow()
  p <- X |> ncol()
  q <- Y |> ncol()
  # allocating theta to weights and biases
  index <- 1:(p*m[1])
  W1 <- matrix(theta[index],p,m[1])     # p*m1
  index <- max(index)+ 1:(m[1]*m[2])
  W2 <- matrix(theta[index],m[1],m[2])  # m1*m2
  index <- max(index)+ 1:(m[2]*q)
  W3 <- matrix(theta[index],m,q)        # m2*q
  index <- max(index)+ 1:m[1]
  b1 <- matrix(theta[index],m[2],1)     # m1*1
  index <- max(index)+ 1:m[2]
  b2 <- matrix(theta[index],m[2],1)     # m2*1
  index <- max(index)+ 1:q
  b3 <- matrix(theta[index],q,1)        # q*1
  
  # Forward Evaluation of network
  ones <- matrix(1,1,N) # vector of 1s transposed 1*N
  #  inputs  
  A0   <- t(X)                          # p*N
  A1   <- sig1(t(W1)%*%A0+b1%*%ones)    # m1*N
  A2   <- sig2(t(W2)%*%A1+b2%*%ones)    # m2*N
  A3   <- sig3(t(W3)%*%A2+b3%*%ones)    # q*N
  Yhat <- t(A3)                         # N*q
  E1 <- g(Yhat,Y)
  E2 <- E1 +nu*(sum(W1^2,W2^2,W3^2)) #SSE_penalised
  return(list(Yhat = Yhat, E1 = E1, E2 = E2)) #could return mse, 
} #but does not matter when not comparing between different Ns
```
```{r}
#|label: game

set.seed(0)

# colours <- viridisLite::viridis(n=3,alpha=0.7,begin=0.2,end=0.8,option="B")

colours <- c("bound" = 'firebrick',
             "finish"= 'limegreen',
             "start" = 'hotpink',
             "obst"  = 'forestgreen')

base_field <- generate_field(colours)

# base_field

obst <- cbind(X_1 = runif(n_obst, obst_bounds[1,1],obst_bounds[2,1]),
              X_2 = runif(n_obst, obst_bounds[1,2],obst_bounds[2,2]),
              Size= rep(obst_size, n_obst))

field_obst <- generate_obstacles(obst, colours[4])
field <- base_field+field_obst
# field
# field + drone

runs <- 10
state <- matrix(NA,nrow=iterlim,ncol=runs)

#initial theta
theta <- 

for(r in 1:runs){
  k <- 0
  x <- c(runif(n=1,start_bounds[,1]),
         start_bounds[1,2])
  field
  while(state[k,r]==0||k==0){ #only the first condition will be checked for the 
    # most part (exceptional condition (thus do-while); shouldn't add overhead)
    k <- k+1
    
    c <- MODEL(x, theta)
    new_x <- x + c*delta
    
    sk <- eval_game_state(new_x)
    state[k,r] <- sk
    
    if (sk == -1){
      on_game_loss()
    }
    if (sk == 1){
      on_game_win()
    }
    if (sk == 0){
      new_x <- x + c*delta
  
      state <- eval_game_state(new_x)
    }
  }
}

```

# Validation Analysis

```{r}
#| label: val-analysis
#| echo: true

n_val <- 10
nu_seq <- exp(seq(-20,10,length= n_val))
#should give us a progress bar, while computing the validation error for 
#this neural net, for the given nu values. also in parallel
with_progress({
  p <- progressor(along=nu_seq)
  Val_error <- foreach(nu. = nu_seq,
                       .combine = rbind) %dofuture% {
    obj_pen <- function(pars) {af_net(train_X,train_Y,pars,m,nu.)$E2}
    #Validation analysis, per nu
    res_opt = #optimisation function goes here
    res_val = af_net(valid_X,valid_Y,res_opt$estimate,m,0) 
    
    #progress bar iterator: also supplies message
    p(message=sprintf("calculated nu: %g",signif(nu.,4)),amount=1)
    #return, will be combined via rbind
    data.frame(nu=nu., error=res_val$E1, iter=res_opt$iterations, 
               code=res_opt$code)} #tells us state of convergence
},handlers= handler_pbcol( #type of progress bar
    complete   = function(s) cli::bg_cyan(cli::col_white(s)),
    incomplete = function(s) cli::bg_red( cli::col_white(s))))
```

